import Footer from "./components/Footer";
import "./globals.css";

export const metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        {children}
        <Footer />
      </body>
    </html>
  );
}
